export const routerLinks = {
  arrayType: ['vendor', 'retailer', 'van'],
  params: {
    ':type': ':type',
    ':company': ':company',
  },
  TypeTwo: /:type|:company/gi,
  TypeRouter: '/:type/',
  CompanyRouter: '/:company/',
  Register: '/:type/register',
  Login: '/:type/login',
  UIIcon: '/:type/administrator/:company/icons',
  UIMask: '/:type/administrator/:company/mask',
  UIEditor: '/:type/administrator/:company/editor',
  UICSSAnimate: '/:type/administrator/:company/animations',
  UIAlerts: '/:type/administrator/:company/alerts',
  UIButton: '/:type/administrator/:company/button',
  WidgetsToolbar: '/:type/administrator/:company/toolbar',
  WidgetsColumns: '/:type/administrator/:company/column',
  WidgetsSearchBar: '/:type/administrator/:company/searchBar',
  WidgetsChartsEC: '/:type/administrator/:company/charts/ec',
  WidgetsDataTable: '/:type/administrator/:company/datatable',
  WidgetsForm: '/:type/administrator/:company/form',
  WidgetsTransferTree: '/:type/administrator/:company/transferTree',
  WidgetsBaseComponent: '/:type/administrator/:company/baseComponent',
  WidgetsComing: '/:type/administrator/:company/coming',
  WidgetsScreenLock: '/:type/administrator/:company/lock',
  WidgetsGallery: '/:type/administrator/:company/gallery',
  WidgetsResult: '/:type/administrator/:company/result',
  WidgetsPrint: '/:type/administrator/:company/print',
  WidgetsBanner: '/:type/administrator/:company/banner',
  WidgetsLevelRoute: '/:type/administrator/:company/level-route',
  Pages403: '/:type/administrator/:company/403',
  Pages404: '/:type/:company/404',
  Pages500: '/:type/administrator/:company/500',
  BusinessCRUD: '/:type/administrator/:company/crud',
  Blank: '/:type/administrator/:company/blank',
  DropDrag: '/:type/administrator/:company/dropdrag',
  Home: '/:type/home',
  OverviewAudleyToysPage: '/:type/administrator/:company/overviewaudleytoyspage',
  PageDashboardHome: '/:type/administrator/:company/profile'
}
